import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <h1>Página Inicial</h1>
          <nav>
            <a href="/page1">Pagina 1</a>
            <a href="/page2">pagina 2</a>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
